baseURL: "https://kabads.monkeez.org"
disablePathToLower: true
languageCode: en-gb
title: Kabads
paginate: 10
theme: herring-cove
params:
  - showRSSButton: true
  - fadeIn: true
  - params.share:
    - facebook: true
permalinks:
  /: /:year/:month/:day/:title/
relativeURLs: true
uglyURLs: true
